micronaut:
  application:
    name: aggregator
  server:
    port: 9989
    context-path: /aggregator
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/aggregator_database`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    schema-generate: VALIDATE
    dialect: POSTGRES

netty:
  default:
    allocator:
      max-order: 3

jpa.default.properties.hibernate.hbm2ddl.auto: update

liquibase:
  datasources:
    default:
      change-log: db/changelog/changelog-master.yml

app.institutions-server-url: ${APP_INSTITUTIONS_SERVER_URL:`http://localhost:9988/institution`}
