micronaut:
  application:
    name: aggregatorServer
  server:
      port: 9989
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/aggregator_database
    driverClassName: org.postgresql.Driver
    username: root
    password: root
    schema-generate: CREATE_DROP
    dialect: POSTGRES
coherence.session.default.type: grpc
