micronaut:
  application:
    name: institutions
datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/aggregator_database`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    schema-generate: CREATE_DROP
    dialect: POSTGRES
netty:
  default:
    allocator:
      max-order: 3
jpa.default.properties.hibernate.hbm2ddl.auto: update
coherence.session.default.type: grpc
